language: ruby
rvm:
  - 2.2.2
branches:
  only:
  - master
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - cp config/database.yml.travis config/database.yml
  - if [[ "$DB" == "postgresql" ]]; then psql -c 'create database backend_test;' -U postgres; fi
cache: bundler  
services:
  - if [[ "$DB" == "postgresql" ]]; then postgresql fi

notifications:
  slack: taxig8:2fQ1h3yErjKhSIxnNhefdSni
